services:
  pgvector:
    image: 'pgvector/pgvector:0.8.0-pg17'
    environment:
      - 'POSTGRES_DB=rules'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'